- hosts: all
  user: root
  gather_facts: no
  tasks:
    # disable services
    - service: name=iptables state=stopped enabled=no
    - service: name=ip6tables state=stopped enabled=no
    - service: name=auditd state=stopped enabled=no
    - service: name=postfix state=stopped enabled=no

    # disable selinux
    - yum: name=libselinux-python
    - selinux: state=disabled

    # kernel params
    # cf. https://github.com/sonots/isucon3_cheatsheet/blob/master/07.kernel.md
    # cf. http://ebookfan.mobi/web/dev/linux/linux-kernel-tuning.html
    # cf. http://netbuffalo.doorblog.jp/archives/4048147.html

    - sysctl: name=kernel.panic value=60

    - sysctl: name=net.core.rmem_max value=16777216
    - sysctl: name=net.core.wmem_max value=16777216
    - sysctl: name=net.ipv4.tcp_rmem value="4096 87380 16777216"
    - sysctl: name=net.ipv4.tcp_wmem value="4096 87380 16777216"
    - sysctl: name=net.ipv4.tcp_no_metrics_save value=1
    - sysctl: name=net.ipv4.tcp_moderate_rcvbuf value=1

    - sysctl: name=net.core.somaxconn value=10240
    - sysctl: name=net.core.netdev_max_backlog value=10240
    - sysctl: name=net.ipv4.tcp_max_syn_backlog value=10240
    - sysctl: name=net.ipv4.tcp_max_tw_buckets value=360000
    - sysctl: name=net.ipv4.tcp_timestamps value=0
    - sysctl: name=net.ipv4.tcp_rfc1337 value=1
    - sysctl: name=net.ipv4.ip_local_port_range value="10000 64000"
    - sysctl: name=net.ipv4.tcp_fin_timeout value=10
    - sysctl: name=net.ipv4.tcp_keepalive_time value=10
    - sysctl: name=net.ipv4.tcp_keepalive_probes value=2
    - sysctl: name=net.ipv4.tcp_keepalive_intvl value=3

    - sysctl: name=kernel.threads-max value=383441
    - sysctl: name=fs.file-max value=5242880

    # yum repo
    - yum: name=yum-priorities
    - yum: name=yum-utils
    - yum: name=http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
    - yum: name=http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
    - yum: name=http://dev.mysql.com/get/mysql-community-release-el6-3.noarch.rpm

    # install tools
    - yum: name=ntp
    - yum: name=curl
    - yum: name=wget
    - yum: name=w3m
    - yum: name=vim
    - yum: name=git
    - yum: name="@Development Tools"
    - yum: name=ncurses-devel
    - yum: name=bc
    - yum: name=mysql-community-client

    # monitoring tools
    - yum: name=hdparm
    - yum: name=dstat
    - yum: name=htop
